### ISSUE TITLE
Suggestion - return Endpoint after publishing

### ISSUE THREAD

**Issue by mDehning** [roskart/dropwizard-jaxws#13]
After publishing an endpoint, there are cases where some properties of the Enpoint may be needed to be changed or added - for example if you want to set up a custom UserPasswordValidator. Specifically you would want to access _endpoint.setProperties()_

Currently the builder does not offer this and the endpoint reference is only visible within the scope of the _publishEndpoint()_ method in the _JaxWSEnvironment_.

If this method would return the endpoint (as does the original _Endpoint.publish()_ Method by cxf), further configuration would be available.

**Comment by mDehning** [comment]
While reading issue #2  i realize it is not in your interest to expose the endpoint. However an addition to the builder and environment to set properties would be helpful.

**Comment by roskart** [comment]
Ok. EndpointBuilder shall be extended with the following method to enable injecting properties:

`EndpointBuilder properties(Map<String, Object> propeties)`

JAXWSEnvironment.publishEndpoint shall return javax.xml.ws.Endpoint:

`Endpoint publishEndpoint(EndpointBuilder endpointBuilder)`

**Comment by roskart** [comment]
This fix is included in 1.0.3 release.

**Comment by mDehning** [comment]
Release 1.0.3 doe snot contain the updated JaxWSBundle. Method publishEndpoint(Endpoint) is still of return type void

**Comment by roskart** [comment]
Properies can also be provided using EndpointBuilder.properties. Does this work for you?

**Comment by mDehning** [comment]
It does not. I have several manipulations to do, due to the fact that I have to accomodate a proxy and other stuff down the line.

**Comment by roskart** [comment]
Well, I don't see a problem with updating JAXWSBundle - this change will not break existing clients. I missed updating it, since I obviously didn't take enough time. I will fix this as I find the time.  Pull requests are welcome.
