### ISSUE TITLE
Suggestion - give possibility to set the proxy factory binding id for clients

### ISSUE THREAD

**Issue by giovannimele** [roskart/dropwizard-jaxws#14]
Hello,

using your nice framework for SOAP, but encountered some limitation when creating SOAP client.

Would it be possible  to set the proxy factory binding id  (through the client builder)?

   public <T> T getClient(ClientBuilder<T> clientBuilder) {

        JaxWsProxyFactoryBean proxyFactory = new JaxWsProxyFactoryBean();
        proxyFactory.setServiceClass(clientBuilder.getServiceClass());
        proxyFactory.setAddress(clientBuilder.getAddress());
        proxyFactory.setBindingId(clientBuilder.getBindingId()); // Binding id is from SoapBindingFactory class

Thx

GM

**Comment by roskart** [comment]
Helo. Could you please confirm that commit c95399b works for you before version 1.0.5 is released?

**Comment by giovannimele** [comment]
Hi,




I will test it today.




Giovanni








Télécharger Outlook pour Android







On Sun, Jun 10, 2018 at 10:19 PM +0200, "Tadej Roškar" <notifications@github.com> wrote:












Helo. Could you please confirm that commit c95399b works for you before version 1.0.5 is released?
