### ISSUE TITLE
Invalid username or password returns 403 status code.

### ISSUE THREAD

**Issue by jferrater** [roskart/dropwizard-jaxws#20]
When publishing an endpoint with authentication enabled, I noticed that the service returns 403 for invalid username or password.  The soap client is expecting a 401 response which should be the proper response for invalid username or password.

**Comment by roskart** [comment]
You are right, response code should be 401. Thanks

**Comment by roskart** [comment]
Returned HTTP code is not the only problem here. BasicAuthenticationInterceptor should not rely on AuthenticationException being thrown from Dropwizard Authenticator in case of bad credentials. This behavior was based on old Dropwizard versions.
