### ISSUE TITLE
Support for Dropwizard 2.0.0

### ISSUE THREAD

**Issue by sleberknight** [roskart/dropwizard-jaxws#22]
Update Dropwizard version to 2.0.0.

See merge request #21

**Comment by roskart** [comment]
Thanks for the contribution. I'll look into it.

**Comment by roskart** [comment]
I merged pull request #21 and made additional changes:
* 4761450: use dropwizard-bom for managing dropwizard dependencies
* 7c96ab7: fix deprecated API usage
* project version was bumped to 1.2.0-SNAPSHOT (not 2.0.0)

During quick test no regressions appeared. If no new issues appear, I will release version 1.2.0 to Maven Central soon.

**Comment by sleberknight** [comment]
Great thanks!
