### ISSUE TITLE
How to correctly create and pass the request object parameters

### ISSUE THREAD

**Issue by 1cor13** [roskart/dropwizard-jaxws#29]
Dear Team,
I am alittle stuck, I have been following the example code base, for `AccessWsdlFirstServiceResource` however it seems I am passing a request object with missing parameters.
Kindly guide me on how to call the soap endpoint with the correct parameters. Here's my [current scenario at stackoverflow](https://stackoverflow.com/questions/65817925/dropwizard-jaxws-library-soap-client-request)

----
I am consuming a soap service using [dropwizard-jaxws](https://github.com/roskart/dropwizard-jaxws).<br/>
Managed to generate the relevant java classes using **Apache CXF 3.4.** Here's the generated interface `IService`. <br/>
```
    @WebService(targetNamespace = "http://tempuri.org/", name = "IService")
    @XmlSeeAlso({ObjectFactory.class})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public interface IService {
    
        @WebMethod(operationName = "PayBill", action = "http://tempuri.org/IService/PayBill")
        @Action(input = "http://tempuri.org/IService/PayBill", output = "http://tempuri.org/IService/PayBillResponse")
        @WebResult(name = "PayBillResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
        public PayBillResponse payBill(
    
                @WebParam(partName = "parameters", name = "PayBill", targetNamespace = "http://tempuri.org/")
                        PayBill parameters
        );
```
------

I wrote this implementing class `IserviceImpl` in *kotlin*
```

@WebService(endpointInterface = "com.mmm.platform.utility.easy.IService",
        targetNamespace = "http://tempuri.org/",
        name = "IService",
        wsdlLocation = "wsdl/mmm-easy.wsdl")
class IServiceImpl: IService {

    override fun payBill(parameters: PayBill?): PayBillResponse {
        var response = PayBillResponse();
        response.setSctrxnid(parameters?.sctxnid);
        return response;
    }
```
----
This is my dropwizard `Application` class in *kotlin*

```
class UtilityServiceApplication : Application<UtilityServiceConfiguration>() {
    private val jaxWsBundle = JAXWSBundle<Any>()

    override fun initialize(bootstrap: Bootstrap<UtilityServiceConfiguration>?) {
        bootstrap?.addBundle(jaxWsBundle)
    }
    
    override fun run(configuration: UtilityServiceConfiguration?, environment: Environment?) {
        environment!!.jersey().register(
            AccessEasyServiceResource(
                jaxWsBundle.getClient(
                    ClientBuilder(IService::class.java,
                        "http://mmm.hhhhh.xyz/EMTerminalAPI/wsdl.svc")
                        .handlers(AccessEasyClientHandler()))))
    }
}
```
------

Dropwizard resource class `AccessServiceResource` in *kotlin* for end-point `/paybillone`

```

@Path("/paybillone")
@Produces(MediaType.APPLICATION_JSON)
public class AccessServiceResource {
    var serviceClient: IService? = null
    constructor(serviceClient: IService) {
        this.serviceClient = serviceClient;
    }
    @GET
    @Timed
    fun getFoo(): String {
        val of = ObjectFactory()
        var payBill = of.createPayBill()
        payBill.sctxnid = of.createPayBillSctxnid(RandomStringUtils.randomAlphanumeric(15))
        payBill.txntype = of.createPayBillTxntype("1")
        payBill.payeecode = of.createPayBillPayeecode("POWER")
        payBill.accountno = of.createPayBillAccountno("04246483624")
        payBill.phoneno = of.createPayBillPhoneno("0700252181")
        payBill.amount = of.createPayBillAmount("5000")

        var payBillResponse = serviceClient?.payBill(payBill)
        return payBillResponse?.receiptno?.value.toString()
    }
```
----
This call `var payBillResponse = serviceClient?.payBill(payBill)` unfortunately returned an error response message `missing mandatory values` yet I clearly added them to the `payBill` object. <br>
**Qn 1** Is this the correct way of creating the request object, so I get the correct corresponding response `payBillResponse`? <br/>
**Qn 2** How and where should I pass `payBill` so I get the correct response to that call? <br> 
**Qn 3** The other issue is most likely my implementation of `IServiceImpl` is wrong, is it even required?

**Comment by roskart** [comment]
Hello. This is hard to answer without seeing your wsdl. Kotlin client code for one of the example services (HibernateExampleService) looks something like this:

    val person = Person()
    person.fullName = "John Doe"
    person.jobTitle = "foo"

    hibernateExampleService.createPerson(person)

    val persons = hibernateExampleService.persons
    persons.forEach {
        println(it.fullName)
    }

Regarding your third question, IServiceImpl is required only if you wish to expose it as SOAP service.

I am closing this ticket as this problem does not seem to be related to library implementation. If you think that there is a bug in the library, feel free to reopen the issue.
