### ISSUE TITLE
Update cxf because of vulnerabilities

### ISSUE THREAD

**Issue by chris--** [roskart/dropwizard-jaxws#30]
Hi, 

thanks a lot for the lib, which works perfectly fine for a legacy soap endpoint of mine! There is a new cxf version out (`3.4.4`), that again fixes vulnerabilities. My (limited) testing with cxf `3.4.4` and Dropwizard `2.0.23` shows no problems. Do you see any issues upgrading cxf in the library? 

Cheers,
Christian

**Comment by roskart** [comment]
Hello. I am glad that you find the lib useful. I ran some tests and I see no issues. New release should be available soon.

**Comment by chris--** [comment]
Thanks @roskart, that was lightning fast :) ! Updated to the new version and it's running just fine.
