### ISSUE TITLE
Publish artifacts to Maven Central

### ISSUE THREAD

**Issue by javaguruen** [roskart/dropwizard-jaxws#6]
It would be very useful if the artifacts were published to Maven Central. This link http://central.sonatype.org/pages/apache-maven.html is the guide to doing so.

**Comment by roskart** [comment]
I did not release to Maven Central since I was not sure there would be any interest. I will get to it as soon as I have some free time.

**Comment by mlotysz** [comment]
:+1: I join to javaguruen request. It'll be nice to have it official.

**Comment by bitsofinfo** [comment]
Ditto that! bump!

**Comment by OFadero** [comment]
Unfortunately if the artifacts aren't in Maven Central I'm not allowed to use them in my client's projects.

**Comment by roskart** [comment]
This issue shall be resolved in a few days.

**Comment by roskart** [comment]
Resolved in release v0.8.0. Dropwizard-jaxws 0.8.0 is now available in Maven Central using the following Maven coordinates:

    <dependency>
        <groupId>com.github.roskart.dropwizard-jaxws</groupId>
        <artifactId>dropwizard-jaxws</artifactId>
        <version>0.8.0</version>
    </dependency>
